Repository udacity/machine-learning, pull requests merged in 2021-03, with the labels that each got.

#325 Change "student" to "donor"
  projects/finding_donors/finding_donors.ipynb
Labels: typo

#394 Update cifar10_augmentation.ipynb
  projects/practice_projects/cnn/cifar10-augmentation/cifar10_augmentation.ipynb
Labels: bug

#387 Add Frozen mean value in question 1
  projects/customer_segments/customer_segments.ipynb
Labels: improve instructions

#346 fixing docs for url of jupyter notebook issue #345
  projects/boston_housing/README.md
  projects/boston_housing/project_description.md
  projects/customer_segments/README.md
  projects/customer_segments/project_description.md
  projects/digit_recognition/README.md
  projects/digit_recognition/project_description.md
  projects/finding_donors/README.md
  projects/finding_donors/project_description.md
  projects/student_intervention/README.md
  projects/student_intervention/project_description.md
  projects/titanic_survival_exploration/README.md
  projects/titanic_survival_exploration/project_description.md
Labels: improve instructions

#386 Fix feature_importances_ typo
  projects/finding_donors/finding_donors.ipynb
Labels: improve instructions

#385 Update GridSearchCV import path
  projects/finding_donors/finding_donors.ipynb
Labels: library update
